### PR TITLE
#507 - Add "Download" Text to HTML5 Player

### PR DESCRIPTION
**Pull request by edequalsawesome**
Added "Play/Pause", "Rewind 30 Seconds", and "Download Epsiode" anchor text for elements that are using icons for better accessibility with screen readers.

(Also I don't think I borked making this pull request, but if I did, I apologize!)

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
@edequalsawesome thanks for this PR. I'll do my best to review it in the coming week.

We're currently in the process of replacing the currently player with an updated version of the HTML player in the coming weeks, so if you have some time when we release that, I'd appreciate any a11y input you'd be willing to share.

**Comment by edequalsawesome** [comment]
@jonathanbossenger Sure thing, I'd be happy to help however I can!

**Comment by jonathanbossenger** [comment]
@edequalsawesome I hope you don't mind me leaving a comment here. We released the new html player today, and after this PR I made a point of adding the screen-reader-text spans on the new player, everywhere it makes sense to me to do so. (regular HTML player, block player, and Elementor player)

I wonder if you could give it a review yourself, and see if I missed any places where this should also be added.

Thanks

**Comment by edequalsawesome** [comment]
@jonathanbossenger Hey! No worries, @ me whenever, I'm always happy to help however I can 😃 

I'll take a closer look tomorrow, but at a quick glance, the only one I see missing would be the playback speed button on line 31 of the `seriously-simple-podcasting/templates/players/castos-player.php` file -- I would use something like this just to indicate what the 1x does:

`<button data-speed="1" class="player-btn__speed player-btn__speed-<?php echo $episode_id ?>" title="Playback Speed"><span class="screen-reader-text">Playback Speed </span>1x</button>`

I'll dig into this a bit more tomorrow and see if I can find anything else -- the new player looks great, by the way! :: internet high five! ::

**Comment by jonathanbossenger** [comment]
@edequalsawesome thanks so much for that feedback.

In working on tracking any new issues that have arisen from the 2.5.0 release, for a patch update early next week, so if there's any chance you can log this as an issue (and anything else you see relevant to the castos-player.php file), I would appreciate it.

**Pull request merged**
