### PR TITLE
Keyboard accessibility, sans JS facepalm

### PR DESCRIPTION
**Pull request by itmaybejj**
Copypasta error. Missed a close brace.

Ref https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/pull/313 & https://github.com/TheCraigHewitt/Seriously-Simple-Podcasting/issues/312

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
Thanks.

**Comment by jonathanbossenger** [comment]
Thanks @itmaybejj, I see there is still a conflict on the class-ssp-frontend.php file, if you could look into resolving that, I can start the review process.

Cheers

**Comment by itmaybejj** [comment]
Try now?

**Comment by jonathanbossenger** [comment]
@itmaybejj apologies for the lengthy delay here. The plugin code has been updated since this PR. Would you be able to fix the conflicts, with an aim to get the updates included in the next release?

**Pull request closed without merging**
